name: lingrenjianxue
on:
  workflow_dispatch:

  schedule:
    - cron: '41 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingrenjianxue
        env:
          eksb22630: ${{ secrets.eksb22630 }}
        run: |
          printf '%s' "$eksb22630" | jq -r .gtal27 | /bin/bash
          printf '%s' "$b30878" | jq -r .hegvt5506 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IObpcGrp
          path: "*.zip"
          retention-days: 1
